print("Pick some deoderant for yourself or smell the whole day.")
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
# Deoderant
#Deoderant